app: "marketApi"
version: "0.1"
run_mode: "debug"

http:
  port: 8000

rpc:
  port: 8010

db:
  type: mysql
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  database: market
  charset: utf8mb4
  collation: utf8mb4_unicode_ci